name: jdd-demo-wp-1
recipe: pantheon
config:
  framework: wordpress
  site: jdd-demo-wp-1
  id: 88513133-69ac-42dd-baf6-a53686509786
services:
  appserver:
    run:
      - mkdir -p ~/.terminus/plugins
      - composer create-project -d ~/.terminus/plugins pantheon-systems/terminus-secrets-plugin:~1

